version: "3.7"
services:
  adventureland:
    image: al
    volumes:
      - al-data-volume:/appserver/storage
    build:
      context: ./
    restart: always
    ports:
      - "8083:8083"
      - "8000:8000"
  eu1:
    image: al
    build:
      context: ./
    restart: always
    ports:
      - "8022:8022"
    entrypoint: ["/adventureland/node-entrypoint.sh", "EU", "I", "8022"]
    depends_on:
      - adventureland
  us1:
    image: al
    build:
      context: ./
    restart: always
    ports:
      - "8023:8023"
    entrypoint: ["/adventureland/node-entrypoint.sh", "US", "I", "8023"]
    depends_on:
      - adventureland

volumes:
  al-data-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/adventureland/data
